name: agrios_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.6.0
  mqtt_client: ^10.11.3
  image_picker: ^1.1.2
  flutter_local_notifications: ^19.5.0
  geolocator: ^14.0.2
  flutter_tts: ^4.2.2
  speech_to_text: ^7.3.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
